services:
  web:
    build:
      context: .
      dockerfile: ./docker_files/Nginx.Dockerfile
    volumes:
      - ./src:/usr/share/nginx/html/sample.koba-masa.com
      - ./tmp/log/nginx:/var/log/nginx
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d
    ports:
      - 8080:80
